# This rule is not used by the project topi itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the build.topi.tobias.no.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: topi
    app.kubernetes.io/managed-by: kustomize
  name: buildjob-editor-role
rules:
- apiGroups:
  - build.topi.tobias.no
  resources:
  - buildjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - build.topi.tobias.no
  resources:
  - buildjobs/status
  verbs:
  - get
