apiVersion: v1
kind: Secret
metadata:
  name: provider-minio
  namespace: topi-builds
type: Opaque
stringData:
  accessKey: "KGALnqoYQfEI3I2JpqSp"
  accessSecret: "Q2gh49zNwmUcBWPet0qE7ni2mbDAWKUvdKjpFC3f"
